config/routes.rb
Rails.application.routes.draw do

  resources :interviewerfeedbacks
  resources :companies
  resources :skillsets

  get 'candidateschedule' => 'candidateprofiles#new'
  get 'candidateentry' => 'candidatedetails#new'
  get 'interviewerfeed' => 'interviewerfeedbacks#new'
  get 'candidatereports' => 'interviewerfeedbacks#index'
  get 'candidateschedulereports' => 'candidateprofiles#index'
  get 'signup' => 'companies#new'
  get 'sendemailcandidate/:id' =>'interviewerfeedbacks#sendmailcandidate',as:'sendemail'
  get 'schedulereport'=>'candidateprofiles#schedulereport'
  resources :candidatedetails do
    collection do
      get :search
    end
  end

  resources :candidateprofiles do
    collection do
      get :search
    end
  end

  resources :interviewers do
    collection do
      get :search
    end
    collection do
      get :searchinterviewer
    end
  end

  resources :calenders do
    collection do
      get :search
    end
    collection do
      get :searchinterviewer
    end
  end

  get 'signout' => 'application#signout'
  get 'login'  => 'companies#login'
  get 'forgotpassword' => 'companies#forgotpassword'
  post 'forgotpasswor' => 'companies#forgotpasswor'
  post 'credential'  => 'companies#credential'
  root 'companies#login'

end

app/models/calender.rb
class Calender < ActiveRecord::Base
  has_many :candidateprofiles
  scope :calender,->(interviewerid,date,status){where("interviewer_id=? and dateformat=? and status=?",interviewerid,date,status)}
  scope :calenderdata,->(interviewerid,date){where("interviewer_id=? and dateformat=? ",interviewerid,date)}
  scope :interviewer,->(primaryid,secondaryid,status,date){where("primaryskills_id=? and secondaryskills_id=? and status=? and dateformat=?",primaryid,secondaryid,status,date)}

end

app/controllers/calenders_controller.rb
class CalendersController < ApplicationController
  before_action :set_calender, only: [:show, :edit, :update, :destroy]
  before_action :authenticate,:roleauthentication
  respond_to :html,:json
  # GET /calenders
  # GET /calenders.json

  def authenticate
    if ((session[:companyemail]||session[:password]=="")||((session[:companyemail]||session[:password])==nil))
       redirect_to root_url
    end
  end

  def roleauthentication
    redirect_to schedulereport_url if session[:role]=="Recruiter"
  end

  def index
    @calenders = Calender.all
  end

  def  search
    interviewernameid=params[:interviewer_id]
    date=params[:dateformat]
    status="new"
    @detail=Calender.calender(interviewernameid,date,status)
    respond_with(@detail, :include => :status)
  end

  def  searchinterviewer
    candidateps=params[:primaryskills_id]
    candidatess=params[:secondaryskills_id]
    status="new"
    date=params[:dateformat]
    @interviewer=Calender.interviewer(candidateps,candidatess,status,date)
    respond_with(@interviewer, :include => :status)
  end

  # GET /calenders/1
  # GET /calenders/1.json
  def show
  end

  # GET /calenders/newi
  def new
    @calender = Calender.new
  end

  # GET /calenders/1/edit
  def edit

  end

  # POST /calenders
  # POST /calenders.json
  def create
    @interviewer=Interviewer.all
    @interviewer.each do |interviewer|
        params[:calender][:interviewername] = interviewer.interviewername
        params[:calender][:interviewer_id] = interviewer.id
        params[:calender][:primaryskills_id]=interviewer.primaryskills_id
        params[:calender][:secondaryskills_id]=interviewer.secondaryskills_id
        params[:calender][:timeslot]=params["interviewer_#{interviewer.id}"].to_s
        count=Calender.where(interviewer_id:interviewer.id,dateformat:params[:calender][:dateformat]).count;
        @calender = Calender.new(params.require(:calender).permit(:dateformat, :timeslot, :interviewername,:interviewer_id,:status,:primaryskills_id,:secondaryskills_id))
        @calender.save if (params[:calender][:timeslot]!="")&&(count!=1)
    end
    redirect_to calenders_url
  end

  # PATCH/PUT /calenders/1
  # PATCH/PUT /calenders/1.json
  def update
    respond_to do |format|
      interviewer=Calender.find_by(:interviewer_id=>"#{@calender.interviewer_id}",:dateformat=>"#{@calender.dateformat}")
      params[:calender][:interviewer_id] = interviewer.interviewer_id
      params[:calender][:primaryskills_id]=interviewer.primaryskills_id
      params[:calender][:secondaryskills_id]=interviewer.secondaryskills_id
      params[:calender][:timeslot]=params["interviewer_#{interviewer.id}"].to_s
      if @calender.update(params.require(:calender).permit(:dateformat, :timeslot, :interviewername,:interviewer_id,:status,:primaryskills_id,:secondaryskills_id))
        format.html { redirect_to @calender, notice: 'Calender was successfully updated.' }
        format.json { render :show, status: :ok, location: @calender }
      else
        format.html { render :edit }
        format.json { render json: @calender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calenders/1
  # DELETE /calenders/1.json
  def destroy
    @calender.destroy
    respond_to do |format|
      format.html { redirect_to calenders_url, notice: 'Calender was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calender
      @calender = Calender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calender_params
      params.require(:calender).permit(:dateformat, :timeslot, :interviewername,:interviewer_id,:status,:primaryskills_id,:secondaryskills_id)
    end
end

app/helpers/calenders_helper.rb
module CalendersHelper
end

app/views/calenders/_form.html.erb
<%= form_for(@calender) do |f| %>
  <% if @calender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calender.errors.count, "error") %> prohibited this calender from being saved:</h2>

      <ul>
      <% @calender.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!-- <div class="row">
     <div class="col-lg-4 col-lg-offset-4">
         <div class="input-group"> -->
            <div class="form-group">
              <%= f.label :dateformat,"Date" %><br>
              <div class='input-group date' id='datetimepicker4'>
                  <%= f.text_field :dateformat,:class=>"form-control"%>
                      <span class="input-group-addon">
                          <span class="glyphicon glyphicon-calendar"></span>
                    </span>
              </div>
            </div>
             <table class="table table-bordered table-hover">
               <tr>
                 <th><%=check_box_tag "interviewertime[]",1,false,:id=>"interviewer_time"%>Times</th>
                 <% Interviewer.all.each do |interviewer| %>
                 <th>
                   <%=check_box_tag "interviewer_id#{interviewer.id}[]",interviewer.id,false,:id=>"interviewer_ids_#{interviewer.id}"%>
                   <%=interviewer.interviewername%></br>
                 </th>
                 <%=f.hidden_field :interviewername,:value=>"#{interviewer.interviewername}"%>
                 <%=f.hidden_field :interviewer_id,:value=>"#{interviewer.id}"%>
                 <%end%>
               </tr>
               <tbody>
               <tr>
                <% a=["6.30AM","7.00AM","7.30AM","8.00AM","8.30AM","9.00AM"]%>
                <% a.each_with_index do |a,i|%>
                 <tr>
                   <td><%=a%></td>
                   <% Interviewer.all.each do |interviewer| %>
                   <td><%=check_box_tag "interviewer_#{interviewer.id}[]",a,false,:id=>"interviewer_ids_#{interviewer.id}"%></td>
                   <%end%>
                 </tr>
                 <%= f.hidden_field :timeslot,:value =>"#{a}"%>
                <%end%>
              </tr>
            </tbody>
            </table>
          </br>
            <!-- <div class="form-group">
              <%= f.hidden_field :interviewer_id%>
            </div> -->
            <div class="form-group">
              <%= f.hidden_field :status,:value =>"new"%>
            </div>
            <div class="form-group">
              <%= f.hidden_field "companyemail",:class=>"required",:value => session[:companyemail]%>
            </div>
            <div class="form-group">
              <%= f.hidden_field "password",:class=>"required",:value => session[:password]%>
            </div>
        <div class="row">
          <div  class="col-lg-4 col-lg-offset-4">
            <div class="actions">
              <%= f.submit :class=>"btn btn-primary btn-lg",:id=>"interviewersubmit"%>
            </div>
         </div>
        </div>

  <% end %>
<script type="text/javascript">

$('.selectpicker').selectpicker({
    size: "fit",
    showTick:true,
    tickIcon:"",
    showTick:true
});
  var pd = new Date();
  pd.setDate(pd.getDate());
 $('#datetimepicker3').datetimepicker({
     format: 'LT'
   });

  $('#datetimepicker4').datetimepicker({
     format: 'DD-MM-YYYY',
     minDate:pd
   });
  $('th input[type="checkbox"]').click(function(){
    a=$(this).attr('id')
    if($(this).is(':checked'))
    {
      $("input[id='"+a+"']").prop('checked',true)
    }
    else
    {
      $("input[id='"+a+"']").prop('checked',false)
    }
  });
  $("#interviewer_time").click(function(){
    if($(this).is(':checked'))
    {
      $("input[type='checkbox']").prop('checked',true)
    }
    else
    {
      $("input[type='checkbox']").prop('checked',false)
    }
  });
</script>

app/views/calenders/_form1.html.erb
<%= form_for(@calender) do |f| %>
  <% if @calender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calender.errors.count, "error") %> prohibited this calender from being saved:</h2>

      <ul>
      <% @calender.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!-- <div class="row">
     <div class="col-lg-4 col-lg-offset-4">
         <div class="input-group"> -->
            <div class="form-group">
              <%= f.label :dateformat,"Date" %><br>
              <div class='input-group date' id='datetimepicker4'>
                  <%= f.text_field :dateformat,:class=>"form-control",:readonly => true%>
                      <span class="input-group-addon">
                          <span class="glyphicon glyphicon-calendar"></span>
                    </span>
              </div>
            </div>
             <table class="table table-bordered table-hover" id="example">
              <thead>
                <tr>
                 <th><span class="text"><%=check_box_tag "interviewertime[]",1,false,:id=>"interviewer_time"%>Times</span></th>
                 <% interviewer=Calender.find_by(:interviewer_id=>"#{@calender.interviewer_id}",:dateformat=>"#{@calender.dateformat}") %>
                 <th><span class="text">
                   <%=check_box_tag "interviewer_id#{interviewer.id}[]",interviewer.id,false,:id=>"interviewer_ids_#{interviewer.id}"%>
                   <%=interviewer.interviewername%></br>
                   </span>
                 </th>
                 <%=f.hidden_field :interviewername,:value=>"#{interviewer.interviewername}"%>
                 <%=f.hidden_field :interviewer_id,:value=>"#{interviewer.id}"%>
               </tr>
               </thead>

               <tbody>
               <tr>
                <% a=["6.00AM","6.30AM","7.00AM","7.30AM","8.00AM","8.30AM","9.00AM","9.30AM","10.00AM","10.30AM","11.00AM","11.30AM","12.00AM","12.30PM","1.00PM","1.30PM","2.00PM","2.30PM","3.00PM","3.30PM","4.00PM","4.30PM","5.00PM","5.30PM","6.00PM","6.30PM","7.00PM","7.30PM","8.00PM"]%>
                <% a.each_with_index do |a,i|%>
                 <tr>
                   <td><%=a%></td>
                   <% interviewer=Calender.find_by(:interviewer_id=>"#{@calender.interviewer_id}",:dateformat=>"#{@calender.dateformat}") %>
                   <td><%=check_box_tag "interviewer_#{interviewer.id}[]",a,interviewer.timeslot.gsub(/[\[\] "]/,'').split(",").include?(a) ? true:false,:id=>"interviewer_ids_#{interviewer.id}"%></td>
                 </tr>
                 <%end%>
                 <%= f.hidden_field :timeslot,:value =>"#{a}"%>
              </tr>
            </tbody>

          </table>

          </br>
            <!-- <div class="form-group">
              <%= f.hidden_field :interviewer_id%>
            </div> -->
            <div class="form-group">
              <%= f.hidden_field :status,:value =>"new"%>
            </div>
            <div class="form-group">
              <%= f.hidden_field "companyemail",:class=>"required",:value => session[:companyemail]%>
            </div>
            <div class="form-group">
              <%= f.hidden_field "password",:class=>"required",:value => session[:password]%>
            </div>
        <div class="row">
          <div  class="col-lg-4 col-lg-offset-4">
            <div class="actions">
              <%= f.submit :class=>"btn btn-primary btn-lg",:id=>"interviewersubmit"%>
            </div>
         </div>
        </div>

  <% end %>
<script type="text/javascript">

$('.selectpicker').selectpicker({
    size: "fit",
    showTick:true,
    tickIcon:"",
    showTick:true
});

 $('#datetimepicker3').datetimepicker({
     format: 'LT'
   });
   var pd = new Date();
   pd.setDate(pd.getDate()-1);
   //var input = $('#calender_dateformat').attr('value', moment().format("DD-MM-YYYY"));
  $('#datetimepicker4').datetimepicker({
     format: 'DD-MM-YYYY'
   });
   $('#example').DataTable( {
       "scrollX": "1200px",
       "scrollY": "400px",
       "paging" :false,
       "info":false,
       "ordering":false,
       "sDom": 'rtip',
       "columnDefs": [{
        "defaultContent": "-",
         "targets": "_all"
         }]
  });
  $('th input[type="checkbox"]').click(function(){
    a=$(this).attr('id')
    if($(this).is(':checked'))
    {
      $("input[id='"+a+"']").prop('checked',true)
    }
    else
    {
      $("input[id='"+a+"']").prop('checked',false)
    }
  });
  $("#interviewer_time").click(function(){
    if($(this).is(':checked'))
    {
      $("input[type='checkbox']").prop('checked',true)
    }
    else
    {
      $("input[type='checkbox']").prop('checked',false)
    }
  });
</script>
<style type="text/css">
.table > thead > tr > th, .table > thead > tr > td, .table > tbody > tr > th, .table > tbody > tr > td, .table > tfoot > tr > th, .table > tfoot > tr > td {
    padding: 4px;
    line-height: 1.42857;
    vertical-align: top;
    border-top: 1px solid #DDD;
}

</style>

app/views/calenders/edit.html.erb
<h1>Editing Calendar</h1>

<%= render 'form1' %>

<%= link_to 'Show', @calender %> |
<%= link_to 'Back', calenders_path %>

app/views/calenders/index.html.erb
<div class="jumbotron">
<p id="notice"><%= notice %></p>

<h3>Listing Calendar</h3>
<div class="table-responsive">
<table class="datatable table table-bordered table-hover sortable">
  <thead class="bg-success">
    <tr>
      <th class="text-info">Date</th>
      <th class="text-info">Time</th>
      <th class="text-info">Interviewer Name</th>
      <th class="text-info">Interviewer ID</th>
      <th class="text-info">Primary Skills ID</th>
      <th class="text-info">Secondary Skills ID</th>
      <th class="text-info">Status</th>
      <th class="text-info">Show</th>
      <th class="text-info">Edit</th>
      <th class="text-info">Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @calenders.each do |calender| %>
      <tr>
        <td><%= calender.dateformat %></td>
        <td style="font-size:9px"><%= calender.timeslot %></td>
        <td><%= calender.interviewername%></td>
        <td><%= calender.interviewer_id%></td>
        <td><%= calender.primaryskills_id%></td>
        <td><%= calender.secondaryskills_id%></td>
        <td><%= calender.status%></td>
        <td><%= link_to 'Show', calender,:class=>"btn btn-primary btn-sm" %></td>
        <td><%= link_to 'Edit', edit_calender_path(calender),:class=>"btn btn-info btn-sm" %></td>
        <td><%= link_to 'Destroy', calender, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<script type="text/javaScript">
 $('.datatable').DataTable({
    "paging": true,
    "ordering": true,
    "info": true,
    // "scrollX": "100%",
    // "scrollY": "300px"
  });

</script>
<br>
</div>
<%= link_to 'New Calender', new_calender_path,:class=>"btn btn-info btn-md" %>
</div>

app/views/calenders/new.html.erb
<h3 style="margin-left:-100px">Calendar</h3>

<%= render 'form' %>
<div class="row">
   <div class="col-lg-4 col-lg-offset-4">
       <div class="input-group">
        <%= link_to 'Back', calenders_path,:class=>"btn btn-info btn-sm"%>
      </div>
  </div>
</div>

app/views/calenders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @calender.dateformat %>
</p>

<p>
  <strong>Time:</strong>
  <%= @calender.timeslot %>
</p>

<p>
  <strong>Interviewername:</strong>
  <%= @calender.interviewername %>
</p>

<%= link_to 'Edit', edit_calender_path(@calender) %> |
<%= link_to 'Back', calenders_path %>