config/routes.rb
Rails.application.routes.draw do

  resources :interviewerfeedbacks
  resources :companies
  resources :skillsets

  get 'candidateschedule' => 'candidateprofiles#new'
  get 'candidateentry' => 'candidatedetails#new'
  get 'interviewerfeed' => 'interviewerfeedbacks#new'
  get 'candidatereports' => 'interviewerfeedbacks#index'
  get 'candidateschedulereports' => 'candidateprofiles#index'
  get 'signup' => 'companies#new'
  get 'sendemailcandidate/:id' =>'interviewerfeedbacks#sendmailcandidate',as:'sendemail'
  get 'schedulereport'=>'candidateprofiles#schedulereport'
  resources :candidatedetails do
    collection do
      get :search
    end
  end

  resources :candidateprofiles do
    collection do
      get :search
    end
  end

  resources :interviewers do
    collection do
      get :search
    end
    collection do
      get :searchinterviewer
    end
  end

  resources :calenders do
    collection do
      get :search
    end
    collection do
      get :searchinterviewer
    end
  end

  get 'signout' => 'application#signout'
  get 'login'  => 'companies#login'
  get 'forgotpassword' => 'companies#forgotpassword'
  post 'forgotpasswor' => 'companies#forgotpasswor'
  post 'credential'  => 'companies#credential'
  root 'companies#login'

end

app/models/interviewer.rb
class Interviewer < ActiveRecord::Base
  #Relation ship
  belongs_to :skillset
  #user method
  scope :interviewerdetail,->(id){where("id=?",id)}
  scope :interviewer,->(primaryid,secondaryid){where("primaryskills=? or secondaryskills=? ",primaryid,secondaryid)}
end

app/controllers/interviewers_controller.rb
class InterviewersController < ApplicationController
  before_action :set_interviewer, only: [:show, :edit, :update, :destroy]
  respond_to :html,:json
  before_action :authenticate,:roleauthentication

  def authenticate
    if ((session[:companyemail]||session[:password]=="")||((session[:companyemail]||session[:password])==nil))
       redirect_to root_url
    end
  end
  def roleauthentication
    redirect_to schedulereport_url if session[:role]=="Recruiter"
  end


  # GET /interviewers
  # GET /interviewers.json
  def index
    @interviewers = Interviewer.all
  end


  def  search
    interviewername=params[:id]
    @detail=Interviewer.interviewerdetail(interviewername)
    respond_with(@detail, :include => :status)
  end

  def  searchinterviewer
    candidateps=params[:primaryskills]
    candidatess=params[:secondaryskills]
    @interviewer=Interviewer.interviewer(candidateps,candidatess)
    respond_with(@interviewer, :include => :status)
  end
  # GET /interviewers/1
  # GET /interviewers/1.json
  def show
  end

  # GET /interviewers/new
  def new
    @interviewer = Interviewer.new
  end

  # GET /interviewers/1/edit
  def edit
  end

  # POST /interviewers
  # POST /interviewers.json
  def create
    @interviewer = Interviewer.new(interviewer_params)

    respond_to do |format|
      if @interviewer.save
        format.html { redirect_to @interviewer, notice: 'Interviewer was successfully created.' }
        format.json { render :show, status: :created, location: @interviewer }
      else
        format.html { render :new }
        format.json { render json: @interviewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interviewers/1
  # PATCH/PUT /interviewers/1.json
  def update
    respond_to do |format|
      if @interviewer.update(interviewer_params)
        format.html { redirect_to @interviewer, notice: 'Interviewer was successfully updated.' }
        format.json { render :show, status: :ok, location: @interviewer }
      else
        format.html { render :edit }
        format.json { render json: @interviewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interviewers/1
  # DELETE /interviewers/1.json
  def destroy
    @interviewer.destroy
    respond_to do |format|
      format.html { redirect_to interviewers_url, notice: 'Interviewer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interviewer
      @interviewer = Interviewer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interviewer_params
      params.require(:interviewer).permit(:interviewername, :interviewercompany,:companyemail,:primaryskills,:primaryskills_id,:secondaryskills,:secondaryskills_id,:otherskills)
    end
end

app/helpers/interviewers_helper.rb
module InterviewersHelper
end

app/views/interviewers/_form.html.erb
<%= form_for(@interviewer) do |f| %>
  <% if @interviewer.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@interviewer.errors.count, "error") %> prohibited this interviewer from being saved:</h4>

      <ul>
      <% @interviewer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
     <div class="col-lg-4 col-lg-offset-4">
         <div class="input-group">
            <div class="form-group">
              <%= f.label :interviewername,"Interviewer Name" %><br>
              <%= f.text_field :interviewername,:placeholder=>"Interviewer Name",:class=>"form-control required",:required=>true%>
            </div>
            <div class="field">
              <%= f.label :interviewercompany,"Interviewer Company" %><br>
              <%= f.text_field :interviewercompany,:placeholder=>"Interviewer Company",:class=>"form-control required",:required=>true %>
            </div>
            <div class="field">
              <%= f.label :companyemail,"Company Email"%><br>
              <%= f.text_field :companyemail ,:placeholder=>"Company Email",:class=>"form-control required",:required=>true%>
            </div>
            <div class="form-group">
              <%= f.label :primaryskills_id,"Primary Skills"%><br>
              <%= f.select :primaryskills_id,options_for_select(Skillset.all.collect{|ss| [ss.skills, ss.id]}),{:prompt => "-- Select Primary Skills --"},{ class: "selectpicker", data: {live_search: 'true',width:"auto" }}%>
            </div>

            <div class="field">
              <%= f.label :secondaryskills_id,"Secondary Skills"%><br>
              <%= f.select :secondaryskills_id,options_for_select(Skillset.all.collect{|ss| [ss.skills, ss.id]}),{:prompt => "-- Select Secondary Skills --"},{ class: "selectpicker", data: {live_search: 'true',width:"auto" }} %>
            </div>
            <div class="form-group">
              <%= f.hidden_field :primaryskills%>
            </div>
            <div class="form-group">
              <%= f.hidden_field :secondaryskills%>
            </div>
            <div class="field">
              <%= f.label :otherskills,"Other Skills"%><br>
              <%= f.text_field :otherskills,:placeholder=>"Other Skills",:class=>"form-control required",:required=>true%>
            </div>
            <div class="form-group">
              <%= f.hidden_field "companyema",:class=>"required",:value => session[:companyemail]%>
            </div>
            <div class="form-group">
              <%= f.hidden_field "password",:class=>"required",:value => session[:password]%>
            </div>
         </div>
      </div>
            <div class="row">
              <div  class="col-lg-4 col-lg-offset-4">
              <div class="actions">
              <%= f.submit :class=>"btn btn-primary btn-md",:id=>"interviewersubmit"%>
            </div>
          </div>
        </div>

</div>
<% end %>

<script type="text/javascript">
$('.selectpicker').selectpicker({
    size: "fit",
    showTick:true,
    tickIcon:"",
    showTick:true
});
$('#interviewer_primaryskills_id').change(function(){
  var text=$('#interviewer_primaryskills_id option:selected').text();
  $('#interviewer_primaryskills').val(text);

});
$('#interviewer_secondaryskills_id').change(function(){
  var text=$('#interviewer_secondaryskills_id option:selected').text();
  $('#interviewer_secondaryskills').val(text);
});
$('input[type="text"]').focusout(function(){
   if($(this).val()=="")
   {
     $(this).css({"border-color":"red","border-width":"2px"});
   }
   else
   {
     $(this).css({"border-color":"skyblue"});
   }
});
$('input[type="number"]').focusout(function(){
   if($(this).val()=="")
   {
     $(this).css({"border-color":"red","border-width":"2px"});
   }
   else
   {
     $(this).css({"border-color":"skyblue"});
   }
});
$('select').focusout(function(){
   if($(this).val()=="")
   {
     $(this).css({"border-color":"red","border-width":"2px"});
   }
   else
   {
     $(this).css({"border-color":"skyblue"});
   }
});
</script>

app/views/interviewers/_form.html.haml
%div{"ng-app" => "interviewerform"}
  = form_for(@interviewer) do |f|
    - if @interviewer.errors.any?
      #error_explanation
        %h4
          = pluralize(@interviewer.errors.count, "error")
          prohibited this interviewer from being saved:
        %ul
          - @interviewer.errors.full_messages.each do |message|
            %li= message
    .row{"ng-controller" => "interviewcontroller"}
      .col-lg-4.col-lg-offset-4
        .input-group
          .field
            = f.label :interviewername,"Interviewer Name"
            %br/
            = f.text_field :interviewername,"ng-style"=>"color",:placeholder=>"Interviewer Name"
          .field
            = f.label :interviewercompany,"Interviewer Company"
            %br/
            = f.text_field :interviewercompany,"ng-style"=>"color",:placeholder=>"Interviewer Company"
          .field
            = f.label :companyemail,"Company Email"
            %br/
            = f.text_field :companyemail,"ng-style"=>"color",:placeholder=>"Comapany Email"
          .field
            = f.label :skills,"Skills"
            %br/
            = f.select :skills,options_from_collection_for_select(Skillset.all,"id","skills"),:prompt=>"--Select Skills--"
          .actions
            = f.submit
:javascript
  $('input[type="text"]').focusout(function(){
     if($(this).val()=="")
     {
       $(this).css({"border-color":"red","border-width":"2px"});
     }
     else
     {
       $(this).css({"border-color":"skyblue"});
     }
  });
  $('input[type="number"]').focusout(function(){
     if($(this).val()=="")
     {
       $(this).css({"border-color":"red","border-width":"2px"});
     }
     else
     {
       $(this).css({"border-color":"skyblue"});
     }
  });
  $('select').focusout(function(){
     if($(this).val()=="")
     {
       $(this).css({"border-color":"red","border-width":"2px"});
     }
     else
     {
       $(this).css({"border-color":"skyblue"});
     }
  });

app/views/interviewers/edit.html.erb
<div class="jumbotron">
<h3>Editing Interviewer</h3>

<%= render 'form' %>

<%= link_to 'Show', @interviewer ,:class=>"btn btn-info btn-sm"%> |
<%= link_to 'Back', interviewers_path, :class=>"btn btn-info btn-sm"%>
</div>

app/views/interviewers/edit.html.haml
%h1 Editing Interviewer
= render 'form'
= link_to 'Show', @interviewer
|
= link_to 'Back', interviewers_path

app/views/interviewers/index.html.erb
<div class="jumbotron">
<p id="notice"><%= notice %></p>

<h3>Listing Interviewers</h3>
<div class="table-responsive">
<table class="table table-bordered table-hover sortable">
  <thead class="bg-success">
    <tr>
      <th class="text-info">Interviewer Name</th>
      <th class="text-info">Interviewer Company</th>
      <th class="text-info">Company Email</th>
      <th class="text-info">Primary Skills</th>
       <th class="text-info">Secondary Skills</th>
       <th class="text-info">Other Skills</th>
       <th class="text-info">Show</th>
       <th class="text-info">Edit</th>
       <th class="text-info">Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @interviewers.each do |interviewer| %>
      <tr>
        <td><%= interviewer.interviewername%></td>
        <td><%= interviewer.interviewercompany %></td>
          <td><%= interviewer.companyemail%></td>
          <td><%= interviewer.primaryskills%></td>
          <td><%= interviewer.secondaryskills%></td>
          <td><%= interviewer.otherskills%></td>
        <td><%= link_to 'Show', interviewer,:class=>"btn btn-primary btn-sm"%></td>
        <td><%= link_to 'Edit', edit_interviewer_path(interviewer),:class=>"btn btn-info btn-sm" %></td>
        <td><%= link_to 'Destroy', interviewer, method: :delete,:class=>"btn btn-danger btn-sm", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>
<%= link_to 'New Interviewer', new_interviewer_path,:class=>"btn btn-primary btn-md"%>
</div>

app/views/interviewers/index.html.haml
%p#notice= notice
%h1 Listing Interviewers
.table-responsive
  %table.table.table-bordered.table-hover.sortable
    %thead.bg-success
      %tr
        %th.text-info Interviewername
        %th.text-info Interviewercompany
        %th.text-info CompanyEmail
        %th.text-info Skills
        %th{:colspan => "3"}
    %tbody
      - @interviewers.each do |interviewer|
        %tr
          %td= interviewer.interviewername
          %td= interviewer.interviewercompany
          %td= interviewer.companyemail
          %td= interviewer.skills
          %td= link_to 'Show', interviewer,:class=>"btn btn-primary btn-sm"
          %td= link_to 'Edit', edit_interviewer_path(interviewer),:class=>"btn btn-info btn-sm"
          %td= link_to 'Destroy', interviewer, method: :delete,:class=>"btn btn-danger btn-sm", data: { confirm: 'Are you sure?' }
  %br/
= link_to 'New Interviewer', new_interviewer_path

app/views/interviewers/new.html.erb
<div class='jumbotron'>
<h3 style="margin-left:-100px">Interviewer</h3>

<%= render 'form' %>
<div class="row">
   <div class="col-lg-4 col-lg-offset-4">
       <div class="input-group">
      <%= link_to 'Back', interviewers_path,:class=>"btn btn-warning btn-md",:style=>"width:250px"%>
  </div>
</div>
</div>
</div>

app/views/interviewers/new.html.haml
%h1 New Interviewer
= render 'form'
= link_to 'Back', interviewers_path

app/views/interviewers/show.html.erb
<div class="jumbotron">
<p id="notice"><%= notice %></p>

<p>
  <strong>Interviewername:</strong>
  <%= @interviewer.interviewername %>
</p>

<p>
  <strong>Interviewercompany:</strong>
  <%= @interviewer.interviewercompany %>
</p>
<p>
  <strong>Primary Skills:</strong>
  <%= @interviewer.primaryskills %>
</p>
<p>
  <strong>Primary Skills ID:</strong>
  <%= @interviewer.primaryskills_id %>
</p>
<p>
  <strong>Secondary  Skills:</strong>
  <%= @interviewer.secondaryskills %>
</p>
<p>
  <strong>Secondary Skills ID:</strong>
  <%= @interviewer.secondaryskills_id %>
</p>
<p>
  <strong>Other Skills:</strong>
  <%= @interviewer.otherskills %>
</p>


<%= link_to 'Edit', edit_interviewer_path(@interviewer) ,:class=>"btn btn-info btn-sm"%> |
<%= link_to 'Back', interviewers_path ,:class=>"btn btn-info btn-sm"%>
<div>

app/views/interviewers/show.html.haml
%p#notice= notice
%p
  %strong Interviewername:
  = @interviewer.interviewername
%p
  %strong Interviewercompany:
  = @interviewer.interviewercompany
%p
  %strong Skills:
  = @interviewer.skills
= link_to 'Edit', edit_interviewer_path(@interviewer)
|
= link_to 'Back', interviewers_path