config/routes.rb
Rails.application.routes.draw do

  resources :interviewerfeedbacks
  resources :companies
  resources :skillsets

  get 'candidateschedule' => 'candidateprofiles#new'
  get 'candidateentry' => 'candidatedetails#new'
  get 'interviewerfeed' => 'interviewerfeedbacks#new'
  get 'candidatereports' => 'interviewerfeedbacks#index'
  get 'candidateschedulereports' => 'candidateprofiles#index'
  get 'signup' => 'companies#new'
  get 'sendemailcandidate/:id' =>'interviewerfeedbacks#sendmailcandidate',as:'sendemail'
  get 'schedulereport'=>'candidateprofiles#schedulereport'
  resources :candidatedetails do
    collection do
      get :search
    end
  end

  resources :candidateprofiles do
    collection do
      get :search
    end
  end

  resources :interviewers do
    collection do
      get :search
    end
    collection do
      get :searchinterviewer
    end
  end

  resources :calenders do
    collection do
      get :search
    end
    collection do
      get :searchinterviewer
    end
  end

  get 'signout' => 'application#signout'
  get 'login'  => 'companies#login'
  get 'forgotpassword' => 'companies#forgotpassword'
  post 'forgotpasswor' => 'companies#forgotpasswor'
  post 'credential'  => 'companies#credential'
  root 'companies#login'

end

app/models/company.rb
class Company < ActiveRecord::Base
#  validates_presence_of :companyname,:companyaddress,:contactperson,:contactnumber
#  validates_uniqueness_of :companyemail
  validates_format_of :companyemail, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_confirmation_of  :password
 # has_secure_password
  scope :allwhere,->(companyemail,password){where("companyemail=? AND password=? ",companyemail,password)}
  scope :password,->(companyemail){where("companyemail=?",companyemail)}
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  layout false
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

   def credential
     @check=Company.allwhere(params[:company][:companyemail],params[:company][:password]).count
    respond_to do |format|
        if @check>=1
          session[:comapanyemail]=params[:company][:companyemail]
          session[:password]=params[:company][:password]
          rol=Company.allwhere(params[:company][:companyemail],params[:company][:password])
          session[:role]=rol[0].role
          format.html { redirect_to schedulereport_url }
        else
          format.html { redirect_to login_url}
          flash[:error] = "Invalid Email and Password"
        end
    end
   end



 def  login
    render "login"
 end

 def forgotpasswor
     @mailid=Company.password(params[:company][:companyemail]);
    respond_to do |format|
     if @mailid.count >= 1
       UserNotifier.send_forgotpassword(@mailid).deliver_now
       format.html { redirect_to forgotpassword_url, notice: 'Password Send to mail '}
     else
      format.html { redirect_to forgotpassword_url}
      flash[:error] = "Enter Correct Email"
     end
   end
 end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        UserNotifier.send_signup_email(@company).deliver_now
        format.html { redirect_to signup_url, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { redirect_to signup_url}
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:companyemail,:password,:password_confirmation,:role)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Interviewer App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="body">
  <div class="login-form">
    <div class="thumbnail">
      <img src="assets/Markuci.png" style="margin-top: -20px;"/>
    </div>
   <%= form_for(@company) do |f| %>
        <% if @company.errors.any? %>
          <div class="alert alert-danger fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <p><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</p>
            <ul>
            <% @company.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <% if flash[:notice] -%>
        <div class="alert alert-success fade in">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <%= flash[:notice] %>
         </div>
         <% end -%>
        <div class="row">
               <div class="input-group">
               <div class="form-group">
                <%= f.label :companyemail,"Company Email",:style=>"color:orange" %><br>
                <%= f.text_field :companyemail,:placeholder=>"Email",:class => "form-control required",:required => true,:onblur=>"validateEmail(this);"%>
              </div>
              <div class="form-group">
                <%= f.label :password,"Password",:style=>"color:orange" %><br>
                <%= f.password_field :password,:placeholder=>" Password",:class => "form-control required",:required => true%>
              </div>
              <div class="form-group">
                <%= f.label :password_confirmation,"Password Confirmation",:style=>"color:orange" %><br>
                <%= f.password_field :password_confirmation,:placeholder=>"Confirm Password",:class => "form-control required",:required => true %>
              </div>
              <div class="form-group">
                <%= f.label :role,"Role",:style=>"color:orange" %><br>
                <%b=["Interviewer","Recruiter"]%>
                <% b.each do |a|%>
                <%= f.radio_button :role,a,:style=>"color:red" %> <label style="color:white"><%=a%></label>
                <% end %>
              </div>
              <div class="form-group">
              <input name="cecky" id="checky" value="1" type="checkbox" /><label style="color:white" class="terms">I accept the terms of use</label>
              </div>
              <div class="actions">
                <%= f.submit :class=>"btn btn-primary btn-md" %>
              </div>
              <%= link_to 'Login', root_path,:class=>"btn btn-primary btn-md",:id=>"link"%>

           </div>
        </div>
<% end %>
</div>
</div>
<script type="text/javascript">


  function isNumberKey(evt)
    {
       var charCode = (evt.which) ? evt.which : event.keyCode
       if (charCode > 31 && (charCode < 48 || charCode > 57))
          return false;
       return true;
    }
    function validateEmail(emailField)
    {
        var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

        if (reg.test(emailField.value) == false)
        {
               $('#company_companyemail').css({"border-color":"red","border-width":"2px"});
            return false;
        }

        return true;
     }

    $('input[type="submit"]').click(function(){
       if($('#company_companyemail').val()=="")
       {
         $('#company_companyemail').css({"border-color":"red","border-width":"2px"});
       }
       if($('#company_password').val()=="")
       {
         $('#company_password').css({"border-color":"red","border-width":"2px"});
       }
       if($('#company_password_confirmation').val()=="")
       {
         $('#company_password_confirmation').css({"border-color":"red","border-width":"2px"});
       }
       else
       {
          $('#company_companyemail').css({"border-color":"skyblue"});
          $('#company_password').css({"border-color":"skyblue"});
          $('#company_password_confirmation').css({"border-color":"skyblue"});
       }
    });
    $('#company_companyemail').focusout(function(){
      if($(this).val().length==0)
      {
        $(this).css({"border-color":"red","border-width":"2px"});
      }
      else
      {
        $(this).css({"border-color":"skyblue"});
      }
    });

    $('input[type="password"]').focusout(function(){
       if($(this).val()=="")
       {
         $(this).css({"border-color":"red","border-width":"2px"});
       }
       else if($(this).val().length<6)
       {
         $(this).css({"border-color":"orange","border-width":"2px"});
       }
       else
       {
         $(this).css({"border-color":"skyblue"});
       }
    });


</script>

</body>
</html>

app/views/companies/_form.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Interviewer App
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.body
    .login-form
      .thumbnail
        %img{:src => "assets/Markuci.png", :style => "margin-top: -20px;"}/
      = form_for(@company) do |f|
        - if @company.errors.any?
          .alert.alert-danger.fade.in
            %a.close{"aria-label" => "close", "data-dismiss" => "alert", :href => "#"} ×
            %p
              = pluralize(@company.errors.count, "error")
              prohibited this company from being saved:
            %ul
              - @company.errors.full_messages.each do |message|
                %li= message
        - if flash[:notice]
          .alert.alert-success.fade.in
            %a.close{"aria-label" => "close", "data-dismiss" => "alert", :href => "#"} ×
            = flash[:notice]
        .row
          .input-group{"ng-app" => "myapp"}
            .field{"ng-controller" => "mycontroll"}
              = f.text_field :companyname,:placeholder=>"Company name",:class => "form-control required",:required=>true
            .field
              = f.text_area :companyaddress,:placeholder=>"Company address",:class => "form-control required",:required=>true,:id=>"textarea"
            .form-group
              = f.text_field :contactperson,:placeholder=>"Contact person",:class => "form-control required",:required=>true
            .form-group
              = f.text_field :contactnumber,:placeholder=>"Contact number",:class => "form-control required",:required => true,:onkeypress=>"return isNumberKey(event)"
            .form-group
              = f.text_field :companyemail,:placeholder=>"Email",:class => "form-control required",:required => true
            .form-group
              = f.password_field :password,:placeholder=>" Password",:class => "form-control required",:required => true
            .form-group
              = f.password_field :password_confirmation,:placeholder=>"Confirm Password",:class => "form-control required",:required => true
            .form-group
              %input#checky{:name => "cecky", :type => "checkbox", :value => "1"}/
              %label.terms{:style => "color:white"} I accept the terms of use
            .actions
              = f.submit :class=>"btn btn-primary btn-md"
            = link_to 'Login', root_path,:class=>"btn btn-primary btn-md",:id=>"link"
    :javascript
      var app=angular.module("myapp",[]);
      app.controller("mycontroll",function($scope){
          
      });


      function isNumberKey(evt)
        {
           var charCode = (evt.which) ? evt.which : event.keyCode
           if (charCode > 31 && (charCode < 48 || charCode > 57))
              return false;
           return true;
        }
        $('input[type="password"]').focusout(function(){
           if($(this).val()=="")
           {
             $(this).css({"border-color":"red","border-width":"2px"});
           }
           else if($(this).val().length<6)
           {
             $(this).css({"border-color":"orange","border-width":"2px"});
           }
           else
           {
             $(this).css({"border-color":"lightgreen"});
           }
        });
        $('input[type="text"]').focusout(function(){
           if($(this).val()=="")
           {
             $(this).css({"border-color":"red","border-width":"2px"});
           }
           else
           {
             $(this).css({"border-color":"lightgreen"});
           }
        });
        $('input[type="number"]').focusout(function(){
           if($(this).val()=="")
           {
             $(this).css({"border-color":"red","border-width":"2px"});
           }
           else
           {
             $(this).css({"border-color":"lightgreen"});
           }
        });
        $('select').focusout(function(){
           if($(this).val()=="")
           {
             $(this).css({"border-color":"red","border-width":"2px"});
           }
           else
           {
             $(this).css({"border-color":"lightgreen"});
           }
        });

app/views/companies/edit.html.haml
%h1 Editing Company
= render 'form'
= link_to 'Show', @company
|
= link_to 'Back', companies_path

app/views/companies/forgotpassword.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Interview App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="body">
  <div class="login-form1">
    <div class="thumbnail">
      <img src="assets/Markuci.png" style="margin-top: -19px;"/>
    </div>
  <%= form_for(Company.new,:url => { :action => "forgotpasswor"}) do |f| %>
     <% if flash[:error] -%>
        <p class="alert alert-danger fade in"> <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><%= flash[:error]%></p>
      <% end -%>
      <% if flash[:notice] -%>
         <p class="alert alert-success fade in"> <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><%= flash[:notice]%></p>
       <% end -%>

        <div class="row">
               <div class="input-group">
              <div class="form-group">
                <%= f.text_field :companyemail,:placeholder=>"Company Email" %>
              </div>
              <div class="actions">
                <%= f.submit "Send Password",:class=>"btn btn-primary btn-md" %>
              </div>
              <%= link_to 'Login', root_path,:class=>"btn btn-primary btn-md",:id=>"link"%>
              <!-- <%= link_to 'Sign Up', signup_path,:class=>"btn btn-primary btn-md",:id=>"link"%> -->
            </div>

        </div>
      <% end %>
      </div>
</div>
</body>
</html>

app/views/companies/index.html.erb
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>

<p id="notice"><%= notice %></p>
<h1>Listing Companies</h1>
<div class="table-responsive">
<table class="table table-bordered table-hover sortable">
  <thead class="bg-success">
    <tr>
      <th class="text-info">Companyemail</th>
      <th class="text-info">Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.companyemail %></td>
        <td><%= company.role %></td>
        <td><%= link_to 'Show', company,:class=>"btn btn-primary btn-sm"%></td>
        <td><%= link_to 'Edit', edit_company_path(company),:class=>"btn btn-info btn-sm" %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/index.html.haml
%p#notice= notice
%h1 Listing Companies
.table-responsive
  %table.table.table-bordered.table-hover.sortable
    %thead.bg-success
      %tr
        %th.text-info Companyname
        %th.text-info Companyaddress
        %th.text-info Contactperson
        %th.text-info Contactnumber
        %th.text-info Companyemail
        %th{:colspan => "3"}
    %tbody
      - @companies.each do |company|
        %tr
          %td= company.companyname
          %td= company.companyaddress
          %td= company.contactperson
          %td= company.contactnumber
          %td= company.companyemail
          %td= link_to 'Show', company,:class=>"btn btn-primary btn-sm"
          %td= link_to 'Edit', edit_company_path(company),:class=>"btn btn-info btn-sm"
          %td= link_to 'Destroy', company, method: :delete,:class=>"btn btn-danger btn-sm", data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Company', new_company_path

app/views/companies/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Interview App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="body">
  <div class="login-form1">
    <div class="thumbnail">
      <img src="assets/Markuci.png" style="margin-top: -19px;"/>
    </div>
  <%= form_for(Company.new,:url => { :action => "credential"}) do |f| %>
     <% if flash[:error] -%>
        <p class="alert alert-danger fade in"> <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><%= flash[:error]%></p>
      <% end -%>
      <% if flash[:danger] -%>
         <p class="alert alert-danger fade in"> <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><%= flash[:error]%></p>
       <% end -%>

        <div class="row">
               <div class="input-group">
              <div class="form-group">
                <%= f.text_field :companyemail,:placeholder=>"Company Email" %>
              </div>
              <div class="form-group">
                <%= f.password_field :password,:placeholder=>"Company Password" %>
              </div>
              <div class="checkboxy">
              <input name="cecky" id="checky" value="1" type="checkbox" /><label style="margin-left:20px;color:white">  Remember me</label>
              </div>
              <div class="actions">
                <%= f.submit "Login",:class=>"btn btn-primary btn-md" %>
              </div>
              <%= link_to 'Sign Up', signup_path,:class=>"btn btn-primary btn-md",:id=>"link"%>
              <%= link_to 'Forgot Password?', forgotpassword_path,:id=>"forgotpassword"%>

            </div>

        </div>

      <% end %>
      </div>
</div>
<script type="text/javaScript">
$(document).ready(function(){
  window.navigator=function(){
    location.reload();
  }

});
</script>
</body>
</html>

app/views/companies/login.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Interview App
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.body
    .login-form1
      .thumbnail
        %img{:src => "assets/Markuci.png", :style => "margin-top: -19px;"}/
      = form_for(Company.new,:url => { :action => "credential"}) do |f|
        - if flash[:error]
          %p.alert.alert-danger.fade.in
            %a.close{"aria-label" => "close", "data-dismiss" => "alert", :href => "#"} ×
            = flash[:error]
        - if flash[:danger]
          %p.alert.alert-danger.fade.in
            %a.close{"aria-label" => "close", "data-dismiss" => "alert", :href => "#"} ×
            = flash[:error]
        .row
          .input-group
            .form-group
              = f.text_field :companyemail,:placeholder=>"Company Email"
            .form-group
              = f.password_field :password,:placeholder=>"Company Password"
            .checkboxy
              %input#checky{:name => "cecky", :type => "checkbox", :value => "1"}/
              %label{:style => "margin-left:20px;color:white"} Remember me
            .actions
              = f.submit "Login",:class=>"btn btn-primary btn-md"
            = link_to 'Sign Up', signup_path,:class=>"btn btn-primary btn-md",:id=>"link"

app/views/companies/new.html.haml
= render 'form'
/
  <haml_loud> link_to &#39;Back&#39;, companies_path </haml_loud>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company Email:</strong>
  <%= @company.companyemail %>
</p>


<p>
  <strong>Credential:</strong>
  <%= @company.role %>
</p>

<p>
  <strong>password:</strong>
  <%= @company.password %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/companies/show.html.haml
%p#notice= notice
%p
  %strong Companyname:
  = @company.companyname
%p
  %strong Companyaddress:
  = @company.companyaddress
%p
  %strong Contactperson:
  = @company.contactperson
%p
  %strong Contactnumber:
  = @company.contactnumber
= link_to 'Edit', edit_company_path(@company)
|
= link_to 'Back', companies_path