config/routes.rb
Rails.application.routes.draw do

  resources :interviewerfeedbacks
  resources :companies
  resources :skillsets

  get 'candidateschedule' => 'candidateprofiles#new'
  get 'candidateentry' => 'candidatedetails#new'
  get 'interviewerfeed' => 'interviewerfeedbacks#new'
  get 'candidatereports' => 'interviewerfeedbacks#index'
  get 'candidateschedulereports' => 'candidateprofiles#index'
  get 'signup' => 'companies#new'
  get 'sendemailcandidate/:id' =>'interviewerfeedbacks#sendmailcandidate',as:'sendemail'
  get 'schedulereport'=>'candidateprofiles#schedulereport'
  resources :candidatedetails do
    collection do
      get :search
    end
  end

  resources :candidateprofiles do
    collection do
      get :search
    end
  end

  resources :interviewers do
    collection do
      get :search
    end
    collection do
      get :searchinterviewer
    end
  end

  resources :calenders do
    collection do
      get :search
    end
    collection do
      get :searchinterviewer
    end
  end

  get 'signout' => 'application#signout'
  get 'login'  => 'companies#login'
  get 'forgotpassword' => 'companies#forgotpassword'
  post 'forgotpasswor' => 'companies#forgotpasswor'
  post 'credential'  => 'companies#credential'
  root 'companies#login'

end

app/models/interviewerfeedback.rb
class Interviewerfeedback < ActiveRecord::Base
   validates_presence_of :interviewername,:candidatename,:status
   has_attached_file :attachedfile, styles: {thumbnail: "60x60#"}
   validates_attachment :attachedfile, content_type: { content_type: "application/pdf" }

   #Association Relationship
   belongs_to :candidateprofile
   

   def self.updateschedulestatus id
     a=Candidateprofile.find_by(id:id)
     a.update(status:"interview")
   end

end

app/controllers/interviewerfeedbacks_controller.rb
class InterviewerfeedbacksController < ApplicationController
  before_action :set_interviewerfeedback, only: [:show, :edit, :update, :destroy,:sendmailcandidate]
  before_action :authenticate

  def authenticate
     if ((session[:companyemail]||session[:password]=="")||((session[:companyemail]||session[:password])==nil))
        redirect_to root_url
     end
   end
  # GET /interviewerfeedbacks
  # GET /interviewerfeedbacks.json
  def index
    @interviewerfeedbacks = Interviewerfeedback.all
  end

  # GET /interviewerfeedbacks/1
  # GET /interviewerfeedbacks/1.json
  def show
  end

  # GET /interviewerfeedbacks/new
  def new
    @interviewerfeedback = Interviewerfeedback.new
  end

  # GET /interviewerfeedbacks/1/edit
  def edit
  end

  # POST /interviewerfeedbacks
  # POST /interviewerfeedbacks.json
  def create
    @interviewerfeedback = Interviewerfeedback.new(interviewerfeedback_params)

    respond_to do |format|
      if @interviewerfeedback.save
        Interviewerfeedback.updateschedulestatus(params[:identity])
        format.html { redirect_to interviewerfeed_url, notice: 'Interviewerfeedback was successfully created.' }
        format.json { render :show, status: :created, location: @interviewerfeedback }
      else
        format.html { render :new }
        format.json { render json: @interviewerfeedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interviewerfeedbacks/1
  # PATCH/PUT /interviewerfeedbacks/1.json
  def update
    respond_to do |format|
      if @interviewerfeedback.update(interviewerfeedback_params)
        format.html { redirect_to @interviewerfeedback, notice: 'Interviewerfeedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @interviewerfeedback }
      else
        format.html { render :edit }
        format.json { render json: @interviewerfeedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interviewerfeedbacks/1
  # DELETE /interviewerfeedbacks/1.json
  def destroy
    @interviewerfeedback.destroy
    respond_to do |format|
      format.html { redirect_to interviewerfeedbacks_url }
      format.json { head :no_content }
    end
  end

  def sendmailcandidate
    ExampleMailer.offerletter(@interviewerfeedback).deliver_now
    redirect_to interviewerfeedback_url,notice:"Offer Letter Send successfully for:"+@interviewerfeedback.candidatemail+""
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interviewerfeedback
      @interviewerfeedback = Interviewerfeedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interviewerfeedback_params
      params.require(:interviewerfeedback).permit(:interviewername, :candidatename,:primaryskills,:secondaryskills,:attachedfile, :status,:communication,:technicalskills,:analyticalskills,:attitude,:timemanagement,:commitementtask,:leadership,:teamwork,:creativity,:flexibility,:overallassesment,:scheduletime,:scheduledate,:candidatemail,:othercomment,:communicationcomment,:technicalskillscomment,:analyticalskillscomment,:attitudecomment,:timemanagementcomment,:commitementtaskcomment,:leadershipcomment,:teamworkcomment,:creativitycomment,:flexibilitycomment)
    end
end

app/helpers/interviewerfeedbacks_helper.rb
module InterviewerfeedbacksHelper
end

app/views/interviewerfeedbacks/_form.html.erb
<%= form_for(@interviewerfeedback) do |f| %>
<div class="jumbotron">
<h3 id="header3">Interviewer Feedback</h3>
  <% if @interviewerfeedback.errors.any? %>
  <div class="alert alert-danger fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <div >
      <h4><%= pluralize(@interviewerfeedback.errors.count, "error") %> prohibited this interviewerfeedback from being saved:</h4>

      <ul>
      <% @interviewerfeedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
  <% end %>
  <% if flash[:notice] %>
  <div class="alert alert-success fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= flash[:notice] %>
   </div>
  <% end %>
  <div class="row">
     <div class="col-lg-4 col-lg-offset-2">
         <div class="input-group">
           <div class="field">
             <%= f.label "candidatename","Scheduled Candidate"%><br>
             <%=select_tag 'candidatename',options_from_collection_for_select(Candidateprofile.candidateschedulestatus("schedule"),"id","candidatename"), :prompt => "--Select Candidate--",:class=>"selectpicker","data-live-search"=>"true","data-width"=>"auto",:style=>"width:300px" %>
           </div>
           <div class="form-group">
             <%= f.hidden_field :candidatename%>
           </div>
           <div class="field">
            <%=f.label :interviewername,"Interviewer Name"%><br>
            <%=f.text_field :interviewername,:placeholder=>"Interviewer Name",:class=>"form-control",:readonly=>true%>
           </div>
           <div class="field">
             <%= f.label :primaryskills,"Primary Skills"%><br>
             <%=f.text_field :primaryskills,:class=>"form-control",:placeholder=>"Skills",:readonly=>true%>
           </div>

         </div>
       </div>
       <div class="col-lg-4 col-lg-offset-1">
         <div class="input-group">
           <div class="field">
             <%= f.label :secondaryskills,"Secondary Skills" %><br>
             <%= f.text_field :secondaryskills,:placeholder=>"Secondary Skills",:class => "form-control required",:required => true,:readonly=>true,:style=>"width:300px"%>
           </div>
           <div class="field">
            <%=f.label :scheduledate,"Schedule Date"%><br>
            <%=f.text_field :scheduledate,:class=>"form-control",:placeholder=>"Schedule Date",:readonly=>true%>
           </div>

           <div class="field">
            <%=f.label :scheduletime,"Schedule Time"%><br>
            <%=f.text_field :scheduletime,:placeholder=>"Schedule Time",:class=>"form-control",:readonly=>true%>
           </div>

          <div class="field">
            <%=f.hidden_field :candidatemail,:class=>"form-control"%>
          </div>
        </div>
     </div>
   </div>
  </div>
<div class="jumbotron">
  <h3 id="header3">Feedback(1-N/A,2-Poor,3-Fair,4-Good,5-Excellent)</h3>
  <div class="row">
    <div class="col-lg-4 col-lg-offset-2">
        <div class="input-group">
          <div class="field">
            <%= f.label :technicalskills,"Technical Skills"%><br>
            <% (1..5).each do |a|%>
            <%= f.radio_button :technicalskills,a%>  <%=a%>
            <% end %>
            <%= f.text_area :technicalskillscomment,:placeholder=>"Technical skills Comment",:class => "form-control required",:id=>"select",:required => true%>
          </div>

          <div class="field">
            <%= f.label :communication,"Communication"%><br>
            <% (1..5).each do |a|%>
            <%= f.radio_button :communication, a%>  <%=a%>
            <% end %>
            <%= f.text_area :communicationcomment,:placeholder=>"Communication Comment",:class => "form-control required",:id=>"select",:required => true%>
          </div>
          <div class="field">
            <%= f.label :teamwork,"Teamwork"%><br>
            <% (1..5).each do |a|%>
            <%= f.radio_button :teamwork, a%>  <%=a%>
            <% end %>
            <%= f.text_area :teamworkcomment,:placeholder=>"Teamwork Comment",:class => "form-control required",:id=>"select",:required => true%>
            </div>
            <div class="field">
              <%= f.label :flexibility,"Flexibility"%><br>
              <% (1..5).each do |a|%>
              <%= f.radio_button :flexibility, a%>  <%=a%>
              <% end %>
              <%= f.text_area :flexibilitycomment,:placeholder=>"Flexibility Comment",:class => "form-control required",:id=>"select",:required => true%>
            </div>
            <div class="field">
              <%= f.label :creativity,"Creativity"%><br>
              <% (1..5).each do |a|%>
              <%= f.radio_button :creativity, a%>  <%=a%>
              <% end %>
              <%= f.text_area :creativitycomment,:placeholder=>"Creativity Comment",:class => "form-control required",:id=>"select",:required => true%>
             </div>


           <div class="field">
             <%= f.label :othercomment,"Other Comments" %><br>
             <%= f.text_area :othercomment,:placeholder=>"Other Comments",:class => "form-control required",:required => true,:id=>"selectoc"%>
           </div>


           </div>
         </div>
     <div class="col-lg-4 col-lg-offset-1">
        <div class="input-group">
          <div class="field">
            <%= f.label :analyticalskills,"Analytical&Logical Skills"%><br>
            <% (1..5).each do |a|%>
            <%= f.radio_button :analyticalskills, a%>  <%=a%>
            <% end %>
            <%= f.text_area :analyticalskillscomment,:placeholder=>"Analytical&Logical Skills Comment",:class => "form-control required",:required => true%>
          </div>
          <div class="field">
            <%= f.label :leadership,"Leadership"%><br>
            <% (1..5).each do |a|%>
            <%= f.radio_button :leadership, a%>  <%=a%>
            <% end %>
            <%= f.text_area :leadershipcomment,:placeholder=>"Leadership Comment",:class => "form-control required",:required => true%>
          </div>
          <div class="field">
            <%= f.label :attitude,"Attitude"%><br>
            <% (1..5).each do |a|%>
            <%= f.radio_button :attitude, a%>  <%=a%>
            <% end %>
            <%= f.text_area :attitudecomment,:placeholder=>"Attitude Comment",:class => "form-control required",:required => true%>
          </div>
          <div class="field">
            <%= f.label :timemanagement,"Time Management"%><br>
            <% (1..5).each do |a|%>
            <%= f.radio_button :timemanagement, a%>  <%=a%>
            <% end %>
            <%= f.text_area :timemanagementcomment,:placeholder=>"Time Management Comment",:class => "form-control required",:required => true%>
          </div>
          <div class="field">
           <%= f.label :commitementtask,"Commitement Task"%><br>
           <% (1..5).each do |a|%>
           <%= f.radio_button :commitementtask, a%>  <%=a%>
           <% end %>
           <%= f.text_area :commitementtaskcomment,:placeholder=>"Commitement Task Comment",:class => "form-control required",:required => true%>
           </div>

           <div class="field">
             <%= f.label :overallassesment,"Over All Assesment"%><br>
             <%= f.text_field :overallassesment,:placeholder=>"Over All Assesment",:class=>"form-control",:readonly=>true%>
           </div>
           <div class="field">
             <%= f.label :status,"Status"%><br>
             <%= f.text_field :status,:placeholder=>"Status",:class=>"form-control",:readonly=>"true"%>
           </div>
           <div class="form-group">
             <%= f.label :attachedfile,"Attached File"%><br>
             <%= f.file_field :attachedfile,:class=>"filestyle","date-buttonName"=>"btn-primary","data-buttonBefore"=>"true","data-size"=>"sm","data-placeholder"=>"Choose File"%>
           </div>
          <div class="form-group">
            <%=hidden_field_tag :identity%>
          </div>

          <div class="form-group">
            <%= f.hidden_field "companyemail",:class=>"required",:value => session[:companyemail]%>
          </div>
          <div class="form-group">
            <%= f.hidden_field "password",:class=>"required",:value => session[:password]%>
          </div>
        </div>
       </div>
       <div class="row">
         <div  class="col-lg-4 col-lg-offset-5">
          <div class="actions">
            <%= f.submit :class=>"btn btn-primary btn-lg",:id=>"submit"%>
          </div>
        </div>
        </div>
</div>
<% end %>

<script type="text/javascript">
    $(":file").filestyle({buttonName:"btn-primary",buttonBefore:true,size:"sm",placeholder:"Choose File"});
    $('.selectpicker').selectpicker({
        size: "fit",
        showTick:true,
        tickIcon:"",
        showTick:true
    });
   $('#candidatename').change(function() {
     if($("#candidatename option:selected").index() > 0)
     {
     var q, textmethod, valuemethod;
     q = $(this).val();
     alert(q);
     textmethod = $('#candidatename option:selected').text();
     valuemethod = $('#candidatename option:selected').val();
     $('#interviewerfeedback_candidatename').val(textmethod);
     $('#identity').val(valuemethod);
     $.ajax({
       type: 'GET',
       url: '/candidateprofiles/search',
       dataType: 'json',
       data: {
         'id': q
       },
       success: function(result) {
         var contact, json, parse;
         json = JSON.stringify(result);
         parse = $.parseJSON(json);
         alert(json);
         $('#interviewerfeedback_interviewername').val(parse[0]['interviewername']);
         $('#interviewerfeedback_primaryskills').val(parse[0]['primaryskills']);
         $('#interviewerfeedback_scheduledate').val(parse[0]['scheduledate']);
         $('#interviewerfeedback_scheduletime').val(parse[0]['scheduletime']);
         $('#interviewerfeedback_candidatemail').val(parse[0]['candidateemail']);
         $('#interviewerfeedback_secondaryskills').val(parse[0]['secondaryskills']);
         },
        error: function() {
         alert('Error!');
       }
     });
   }
   else
   {
     $('#interviewerfeedback_interviewername').val("");
     $('#interviewerfeedback_skills').val("");
     $('#interviewerfeedback_scheduledate').val("");
     $('#interviewerfeedback_scheduletime').val("");
     $('#interviewerfeedback_candidatemail').val("");
     $('#interviewerfeedback_yoe').val("");
   }
   });

   $('input[name="interviewerfeedback[commitementtask]"]').change(function(){
        if(!$('input[name="interviewerfeedback[technicalskills]"]:checked').val())
        {
            alert("click technicalskills")
        }
        else
        {
      //  var perso=parseFloat($('input[name="interviewerfeedback[personality]"]:checked').val());
        var commu=parseFloat($('input[name="interviewerfeedback[communication]"]:checked').val());
        var ts=parseFloat($('input[name="interviewerfeedback[technicalskills]"]:checked').val());
        var as=parseFloat($('input[name="interviewerfeedback[analyticalskills]"]:checked').val());
        var jn=parseFloat($('input[name="interviewerfeedback[attitude]"]:checked').val());
        var tm=parseFloat($('input[name="interviewerfeedback[timemanagement]"]:checked').val());
        var ct=parseFloat($('input[name="interviewerfeedback[commitementtask]"]:checked').val());
        var ls=parseFloat($('input[name="interviewerfeedback[leadership]"]:checked').val());
        var tw=parseFloat($('input[name="interviewerfeedback[teamwork]"]:checked').val());
        //var gs=parseFloat($('input[name="interviewerfeedback[goalsettings]"]:checked').val());
        var cr=parseFloat($('input[name="interviewerfeedback[creativity]"]:checked').val());
        var fl=parseFloat($('input[name="interviewerfeedback[flexibility]"]:checked').val());

        var avg;
        avg=parseInt((commu+ts+as+jn+tm+ct+ls+tw+cr+fl)/10);
        $('#interviewerfeedback_overallassesment').val(avg);
         if($('#interviewerfeedback_overallassesment').val()>=3)
         {
           alert($('#interviewerfeedback_overallassesment').val());
           $('#interviewerfeedback_status').val('Pass');
         }
         else
         {
           $('#interviewerfeedback_status').val('Fail');

         }
        }
    });


     $('input[type="submit"]').click(function(){
       if($('input[type="text"]').val()=="")
       {
         $('input[type="text"]').css({"border-color":"red","border-width":"2px"});
       }
      if($('input[type="number"]').val()=="")
       {
         $('input[type="number"]').css({"border-color":"red","border-width":"2px"});
       }
       if($('textarea').val()=="")
       {
          $('textarea').css({"border-color":"red","border-width":"2px"});
       }
       if($('select').val()=="")
       {
         $('select').css({"border-color":"red","border-width":"2px"});
       }
       else
       {
         $('input[type="text"]').css({"border-color":"skyblue"});
         $('input[type="number"]').css({"border-color":"skyblue"});
         $('textarea').css({"border-color":"skyblue"});
         $('select').css({"border-color":"skyblue"});
       }
    });

    $('input[type="text"]').change(function(){
         $(this).css({"border-color":"skyblue"});
    });
    $('input[type="number"]').change(function(){
         $(this).css({"border-color":"skyblue"});
    });
    $('textarea').change(function(){
         $(this).css({"border-color":"skyblue"});
    });
    $('select').change(function(){
         $(this).css({"border-color":"skyblue"});
    });
</script>

app/views/interviewerfeedbacks/edit.html.haml
%h1 Editing Interviewerfeedback
= render 'form'
= link_to 'Show', @interviewerfeedback
|
= link_to 'Back', interviewerfeedbacks_path

app/views/interviewerfeedbacks/index.html.erb
<div class="jumbotron">
<h3>Interviewer Feedbacks</h3>
<div class="table-responsive">
<table class="datatable table table-bordered table-hover sortable" id="example">
  <thead class="bg-success">
    <tr>
      <th class="text-info">Interviewer Name</th>
      <th class="text-info">Candidate Name</th>
      <th class="text-info">Primary Skills</th>
      <th class="text-info">Schedule Date</th>
      <th class="text-info">Schedule Time</th>
      <th class="text-info">Over all Rating</th>
      <th class="text-info">Status</th>
      <th class="text-info" >Show</th>
      <!-- <th class="text-info">Edit</th> -->
      <th class="text-info">Destroy</th>

    </tr>
  </thead>

  <tbody>
    <% @interviewerfeedbacks.each do |interviewerfeedback| %>
      <% if interviewerfeedback.status=="Pass"%>
      <tr bgcolor="#c4f7b8">
        <td><%= interviewerfeedback.interviewername %></td>
        <td><%= interviewerfeedback.candidatename %></td>
        <td><%= interviewerfeedback.primaryskills %></td>
        <td><%= interviewerfeedback.scheduledate %></td>
        <td><%= interviewerfeedback.scheduletime%></td>
        <td><%= interviewerfeedback.overallassesment %></td>
        <td><%= interviewerfeedback.status %></td>
        <td><%= link_to 'Show', interviewerfeedback,:class=>"btn btn-primary btn-sm"%></td>
        <!-- <td><%= link_to 'Edit', edit_interviewerfeedback_path(interviewerfeedback),:class=>"btn btn-info btn-sm" %></td> -->
        <td><%= link_to 'Destroy', interviewerfeedback, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger btn-sm" %></td>
      </tr>
      <% else %>
      <tr bgcolor="#f7b8b8">
        <td><%= interviewerfeedback.interviewername %></td>
        <td><%= interviewerfeedback.candidatename %></td>
        <td><%= interviewerfeedback.skills %></td>
        <td><%= interviewerfeedback.scheduledate %></td>
        <td><%= interviewerfeedback.scheduletime%></td>
        <td><%= interviewerfeedback.overallassesment %></td>
        <td><%= interviewerfeedback.status %></td>
        <td><%= link_to 'Show', interviewerfeedback,:class=>"btn btn-primary btn-sm"%></td>
        <!-- <td><%= link_to 'Edit', edit_interviewerfeedback_path(interviewerfeedback),:class=>"btn btn-info btn-sm" %></td> -->
        <td><%= link_to 'Destroy', interviewerfeedback, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger btn-sm" %></td>
      </tr>
      <%end%>

    <% end %>
  </tbody>
</table>
</div>
<script type="text/javaScript">
 $('.datatable').DataTable({
    "paging": true,
    "ordering": true,
    "info": true,
    // "scrollX":"100%",
    // "scrollY": "300px"
  });



</script>
</div>
<br>

app/views/interviewerfeedbacks/index.html.haml
.jumbotron
  %h3 Interviewer Feedbacks
  .table-responsive
    %table#example.datatable.table.table-bordered.table-hover.sortable
      %thead.bg-success
        %tr
          %th.text-info Interviewer Name
          %th.text-info Candidate Name
          %th.text-info Skills
          %th.text-info Schedule Date
          %th.text-info Schedule Time
          %th.text-info Over all Rating
          %th.text-info Status
          %th.text-info Show
          / <th class="text-info">Edit</th>
          %th.text-info Destroy
      %tbody
        - @interviewerfeedbacks.each do |interviewerfeedback|
          - if interviewerfeedback.status=="Pass"
            %tr{:bgcolor => "#c4f7b8"}
              %td= interviewerfeedback.interviewername
              %td= interviewerfeedback.candidatename
              %td= interviewerfeedback.skills
              %td= interviewerfeedback.scheduledate
              %td= interviewerfeedback.scheduletime
              %td= interviewerfeedback.overallassesment
              %td= interviewerfeedback.status
              %td= link_to 'Show', interviewerfeedback,:class=>"btn btn-primary btn-sm"
              / <td><haml_loud> link_to &#39;Edit&#39;, edit_interviewerfeedback_path(interviewerfeedback),:class=&gt;&quot;btn btn-info btn-sm&quot; </haml_loud></td>
              %td= link_to 'Destroy', interviewerfeedback, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger btn-sm"
          - else
            %tr{:bgcolor => "#f7b8b8"}
              %td= interviewerfeedback.interviewername
              %td= interviewerfeedback.candidatename
              %td= interviewerfeedback.skills
              %td= interviewerfeedback.scheduledate
              %td= interviewerfeedback.scheduletime
              %td= interviewerfeedback.overallassesment
              %td= interviewerfeedback.status
              %td= link_to 'Show', interviewerfeedback,:class=>"btn btn-primary btn-sm"
              / <td><haml_loud> link_to &#39;Edit&#39;, edit_interviewerfeedback_path(interviewerfeedback),:class=&gt;&quot;btn btn-info btn-sm&quot; </haml_loud></td>
              %td= link_to 'Destroy', interviewerfeedback, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger btn-sm"
  %script{:type => "text/javaScript"}
    :cdata
      $('.datatable').DataTable({
      "paging": true,
      "ordering": true,
      "info": true,
      "scrollX":"100%",
      "scrollY": "300px"
      });
%br/

app/views/interviewerfeedbacks/new.html.haml
= render 'form'

app/views/interviewerfeedbacks/show.html.erb
<% if flash[:notice] %>
<div class="alert alert-success fade in">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <%= flash[:notice] %>
 </div>
<% end %>

<div class="jumbotron">
<p>
  <strong>Interviewer Name:</strong>
  <%= @interviewerfeedback.interviewername %>
</p>
<p>
  <strong>Candidate Email:</strong>
  <%= @interviewerfeedback.candidatemail %>
</p>

<p>
  <strong>Candidate Name:</strong>
  <%= @interviewerfeedback.candidatename %>
</p>
<p>
  <strong>Primary Skills:</strong>
  <%= @interviewerfeedback.primaryskills %>
</p>
<p>
  <strong>Secondary Skills:</strong>
  <%= @interviewerfeedback.secondaryskills %>
</p>
<p>
  <strong>Over All Assesment:</strong>
  <%= @interviewerfeedback.overallassesment %>
</p>

<p>
  <strong>Status:</strong>
  <%= @interviewerfeedback.status %>
</p>
<%= link_to 'Send Offer Letter',sendemail_path,:style=>"color:blue"%>
<%= link_to 'Back', interviewerfeedbacks_path %>
</div>

app/views/interviewerfeedbacks/show.html.haml
- if flash[:notice]
  .alert.alert-success.fade.in
    %a.close{"aria-label" => "close", "data-dismiss" => "alert", :href => "#"} ×
    = flash[:notice]
.jumbotron
  %p
    %strong Interviewer Name:
    = @interviewerfeedback.interviewername
  %p
    %strong Candidate Email:
    = @interviewerfeedback.candidatemail
  %p
    %strong Candidate Name:
    = @interviewerfeedback.candidatename
  %p
    %strong Skills:
    = @interviewerfeedback.skills
  %p
    %strong Over All Assesment:
    = @interviewerfeedback.overallassesment
  %p
    %strong Status:
    = @interviewerfeedback.status
  = link_to 'Send Offer Letter',sendemail_path,:style=>"color:blue"
  = link_to 'Back', interviewerfeedbacks_path